# Test creating a contact
# TODO does not properly work, since /set has some bug
---
- hosts: roundcube_servers
  ignore_errors: true
  gather_facts: false
  tasks:
    - name: Create test folder
      ansible.builtin.file:
        dest: "/tmp/openxport_ansible_output/{{ inventory_hostname }}"
        state: directory
        mode: '0755'
      delegate_to: 127.0.0.1

    - name: Create a contact
      uri:
        body: '{"using":["urn:ietf:params:jmap:contacts"],"methodCalls":[["Contact/set", {"accountId":"{{ admin_user }}", "create":{"asd": {"firstName": "Testi"}}}, "0"]]}'
        body_format: json
        force_basic_auth: true #TODO once we return correct 401 we can remove this
        url: "{{ local_address }}"
        url_password: "{{ admin_pass }}"
        url_username: "{{ admin_user }}"
        method: POST
        return_content: true
        validate_certs: false
      delegate_to: 127.0.0.1
      failed_when: "'Contact/set' not in call_response.content"
      register: call_response

    - name: Store reply under /tmp/
      copy:
        content: "{{ call_response.content }}"
        dest: "/tmp/openxport_ansible_output/{{ inventory_hostname }}/\
               contact_set_create.json"
      delegate_to: 127.0.0.1

    - name: Delete it again
      uri:
        body: '{"using":["urn:ietf:params:jmap:contacts"],"methodCalls":[["Contact/set", {"accountId":"{{ admin_user }}", "destroy":["{{ call_response.json.methodResponses[0][1].created.asd.id }}"]}, "0"]]}'
        body_format: json
        force_basic_auth: true #TODO once we return correct 401 we can remove this
        url: "{{ local_address }}"
        url_password: "{{ admin_pass }}"
        url_username: "{{ admin_user }}"
        method: POST
        return_content: true
        validate_certs: false
      delegate_to: 127.0.0.1
      failed_when: "'Contact/set' not in call_response.content"
      register: call_response

    - name: Store reply under /tmp/
      copy:
        content: "{{ call_response.content }}"
        dest: "/tmp/openxport_ansible_output/{{ inventory_hostname }}/\
               contact_set_delete.json"
      delegate_to: 127.0.0.1

    # TODO weird properties seem to be ignored
    - name: Creating an invalid contact should result in an error
      uri:
        body: '{"using":["urn:ietf:params:jmap:contacts"],"methodCalls":[["Contact/set", {"accountId":"{{ admin_user }}", "create":{"asd": {"weirdprop": "Idontexist"}}}, "0"]]}'
        body_format: json
        force_basic_auth: true #TODO once we return correct 401 we can remove this
        url: "{{ local_address }}"
        url_password: "{{ admin_pass }}"
        url_username: "{{ admin_user }}"
        method: POST
        return_content: true
        validate_certs: false
      delegate_to: 127.0.0.1
      failed_when: "'Contact/set' not in call_response.content"
      register: call_response

    - name: Store reply under /tmp/
      copy:
        content: "{{ call_response.content }}"
        dest: "/tmp/openxport_ansible_output/{{ inventory_hostname }}/\
               contact_set_create_invalid.json"
      delegate_to: 127.0.0.1
