# Test creating a contact
# TODO does not properly work, since /set has some bug
---
- hosts: roundcube_servers
  ignore_errors: true
  gather_facts: false
  tasks:
    - name: Create test folder
      ansible.builtin.file:
        dest: "/tmp/openxport_ansible_output/{{ inventory_hostname }}"
        state: directory
        mode: '0755'
      delegate_to: 127.0.0.1

    - name: Create an identity
      uri:
        body: '{"using":["urn:ietf:params:jmap:submission"],"methodCalls":[["Identity/set", {"accountId":"{{ admin_user }}", "create":{"asd": {"textSignature": "I am a text signature"}}}, "0"]]}'
        body_format: json
        force_basic_auth: true #TODO once we return correct 401 we can remove this
        url: "{{ local_address }}"
        url_password: "{{ admin_pass }}"
        url_username: "{{ admin_user }}"
        method: POST
        return_content: true
        validate_certs: false
      delegate_to: 127.0.0.1
      register: call_response

    - name: Store reply under /tmp/
      copy:
        content: "{{ call_response.content }}"
        dest: "/tmp/openxport_ansible_output/{{ inventory_hostname }}/\
               identity_set.json"
      delegate_to: 127.0.0.1

    - debug:
        msg: "No valid response.\n{{ call_response.json }}"
      when: "'Identity/set' not in call_response.content"
      failed_when: true
